### ISSUE TITLE
I just commit my calculator on my github!

### ISSUE THREAD

**Issue by vckfnv** [hochae2018/Java-program-practice-2019#1]
Have a good day professor!
I did my best thank you for your teaching ! :)

**Comment by hochae2018** [comment]
Thanks a lot.

**Comment by YoonSeongKyeong** [comment]
교수님 혹시 슬라이드 없이 실행모습이랑 주요 구현내용 설명하는 정도만 해서 발표할 수 있을까요?? 
금요일날 시험이 있어서요 ㅠㅠ
​
-----Original Message-----

**Comment by hochae2018** [comment]
윤성경님,
가능하면 간단하게라도 자료를 만들어 보십시오.
제 경험상 자료를 만들면서 하고 싶은 말들을 정리하게 됩니다.
물론 발표를 할때 계획대로 다 되지는 않지요…
그래도 준비를 하시는 것이 듣는 사람에게도 도움이 되지만 그보다는 발표자 본인에게 더 많이 도움이 된다고 생각합니다.

준비해 보시고 어려우시면 다시한번 말씀해 주십시오.

hochae

**Comment by YoonSeongKyeong** [comment]
예 알겠습니다!! 자료를 좀 정리해서 보내겠습니다!
진심어린 조언 정말 감사드립니다! :)
​
-----Original Message-----

**Comment by hochae2018** [comment]
윤성경님,
감사합니다. 금요일 시험이 더 중요한 전공시험인 것 같아 죄송하네요…
그리고 보내주신 코드 보고 정말 많은 시간을 쓰셨겠다는 생각에 감사한 마음 한편으로 미안한 마음이 듭니다.

다시한번 감사드립니다.

hochae

**Comment by YoonSeongKyeong** [comment]
아닙니다! 계산기 만들면서 재밌어서 좋았어요 ㅎㅎ 보람도 있고
아무튼 내일 아침까지 슬라이드 만들어서 보내겠습니다!!
​
-----Original Message-----

**Comment by hochae2018** [comment]
감사합니다.

hochae
