### ISSUE TITLE
Calculator commited on Guthub

### ISSUE THREAD

**Issue by jaehchangSCSC** [hochae2018/Java-program-practice-2019#2]
계산기를 깃허브에 올렸습니다.
(Guipractice의 readme도 같이 참고해서 보시면 좋을 것 같습니다.)

**Comment by rrruk** [comment]
calculator 과제 깃허브에 올렸습니다. 추후 수정이 더 들어갈 수 있을 듯 합니다ㅜㅜ

**Comment by hochae2018** [comment]
감사합니다.
