### ISSUE TITLE
계산기 구현에 대해서 발표 신청합니다.

### ISSUE THREAD

**Issue by YoonSeongKyeong** [hochae2018/Java-program-practice-2019#4]
매크로와 결과 창 표현 방식, '(' ')' 구현 등에 대해서 설명한 뒤에, OOP의 클래스 구조와 polymorphism을 어떤 방식으로 계산기에 적용했는지 설명하고 싶습니다.
이번에는 ppt 대신 zoom을 통해서 직접 어떤 코드가 사용되었고 시연모습을 보여드리면서 설명하고 싶습니다.

**Comment by hochae2018** [comment]
Thank you!
